import './globals.css'
import type { Metadata } from 'next'
import Drawer from '@/components/Drawer';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: 'Trello 2.0 clone',
  description: 'Generated by Roshan Bhatta',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=''>
          <Header/>
          <div className='flex pt-[120px] justify-start items-start'>
            <Drawer className='w-2/12 h-screen'/>
              <div className='w-9/12 mx-auto'>
                {children}
              </div>
          </div>
      </body>
    </html>
  )
}
